name: feedback_jira
description: A Flutter package for getting better feedback. It allows the user to give interactive feedback directly in the app and upload it as a ticket in Jira Software
version: 0.0.1
repository: https://github.com/encalv/feedback_jira
issue_tracker: https://github.com/encalv/feedback_jira/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  feedback: ^3.0.0
  http: ^1.0.0
  http_parser: ^4.0.0
  package_info_plus: ^8.1.3
  device_info_plus: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
